# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='lizardsNroachestypes',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0eprotocol.proto\x12\x14lizardsNroachestypes\"2\n\x08Position\x12\x12\n\nposition_x\x18\x01 \x02(\x05\x12\x12\n\nposition_y\x18\x02 \x02(\x05\"\x81\x02\n\x0bGameMessage\x12\x33\n\x08msg_type\x18\x01 \x02(\x0e\x32!.lizardsNroachestypes.MessageType\x12\x11\n\tn_roaches\x18\x02 \x01(\x05\x12\x0f\n\x07n_wasps\x18\x03 \x01(\x05\x12\r\n\x05index\x18\x04 \x01(\x05\x12\x13\n\x0broach_index\x18\x05 \x01(\x05\x12\x12\n\nwasp_index\x18\x06 \x01(\x05\x12\x15\n\rscore_roaches\x18\x07 \x03(\x05\x12\x12\n\nwasps_char\x18\x08 \x03(\x05\x12\x36\n\tdirection\x18\t \x01(\x0e\x32#.lizardsNroachestypes.DirectionType*\xa8\x01\n\x0bMessageType\x12\x13\n\x0fROACHES_CONNECT\x10\x00\x12\x14\n\x10ROACHES_MOVEMENT\x10\x01\x12\x11\n\rWASPS_CONNECT\x10\x02\x12\x12\n\x0eWASPS_MOVEMENT\x10\x03\x12\x07\n\x03\x41\x43K\x10\x04\x12\x10\n\x0cSCORE_UPDATE\x10\x05\x12\x16\n\x12ROACHES_DISCONNECT\x10\x64\x12\x14\n\x10WASPS_DISCONNECT\x10\x65*.\n\nEntityType\x12\x0b\n\x07NOTHING\x10\x00\x12\t\n\x05ROACH\x10\x01\x12\x08\n\x04WASP\x10\x02*6\n\rDirectionType\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03')
)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='lizardsNroachestypes.MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ROACHES_CONNECT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROACHES_MOVEMENT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WASPS_CONNECT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WASPS_MOVEMENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ACK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SCORE_UPDATE', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROACHES_DISCONNECT', index=6, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WASPS_DISCONNECT', index=7, number=101,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=353,
  serialized_end=521,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_ENTITYTYPE = _descriptor.EnumDescriptor(
  name='EntityType',
  full_name='lizardsNroachestypes.EntityType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOTHING', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ROACH', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WASP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=523,
  serialized_end=569,
)
_sym_db.RegisterEnumDescriptor(_ENTITYTYPE)

EntityType = enum_type_wrapper.EnumTypeWrapper(_ENTITYTYPE)
_DIRECTIONTYPE = _descriptor.EnumDescriptor(
  name='DirectionType',
  full_name='lizardsNroachestypes.DirectionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=571,
  serialized_end=625,
)
_sym_db.RegisterEnumDescriptor(_DIRECTIONTYPE)

DirectionType = enum_type_wrapper.EnumTypeWrapper(_DIRECTIONTYPE)
ROACHES_CONNECT = 0
ROACHES_MOVEMENT = 1
WASPS_CONNECT = 2
WASPS_MOVEMENT = 3
ACK = 4
SCORE_UPDATE = 5
ROACHES_DISCONNECT = 100
WASPS_DISCONNECT = 101
NOTHING = 0
ROACH = 1
WASP = 2
UP = 0
DOWN = 1
LEFT = 2
RIGHT = 3



_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='lizardsNroachestypes.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position_x', full_name='lizardsNroachestypes.Position.position_x', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position_y', full_name='lizardsNroachestypes.Position.position_y', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=90,
)


_GAMEMESSAGE = _descriptor.Descriptor(
  name='GameMessage',
  full_name='lizardsNroachestypes.GameMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_type', full_name='lizardsNroachestypes.GameMessage.msg_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_roaches', full_name='lizardsNroachestypes.GameMessage.n_roaches', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_wasps', full_name='lizardsNroachestypes.GameMessage.n_wasps', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='lizardsNroachestypes.GameMessage.index', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roach_index', full_name='lizardsNroachestypes.GameMessage.roach_index', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wasp_index', full_name='lizardsNroachestypes.GameMessage.wasp_index', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score_roaches', full_name='lizardsNroachestypes.GameMessage.score_roaches', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wasps_char', full_name='lizardsNroachestypes.GameMessage.wasps_char', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='direction', full_name='lizardsNroachestypes.GameMessage.direction', index=8,
      number=9, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=350,
)

_GAMEMESSAGE.fields_by_name['msg_type'].enum_type = _MESSAGETYPE
_GAMEMESSAGE.fields_by_name['direction'].enum_type = _DIRECTIONTYPE
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
DESCRIPTOR.message_types_by_name['GameMessage'] = _GAMEMESSAGE
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
DESCRIPTOR.enum_types_by_name['EntityType'] = _ENTITYTYPE
DESCRIPTOR.enum_types_by_name['DirectionType'] = _DIRECTIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:lizardsNroachestypes.Position)
  ))
_sym_db.RegisterMessage(Position)

GameMessage = _reflection.GeneratedProtocolMessageType('GameMessage', (_message.Message,), dict(
  DESCRIPTOR = _GAMEMESSAGE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:lizardsNroachestypes.GameMessage)
  ))
_sym_db.RegisterMessage(GameMessage)


# @@protoc_insertion_point(module_scope)
