/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protocol.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   lizards_nroachestypes__position__init
                     (LizardsNroachestypes__Position         *message)
{
  static const LizardsNroachestypes__Position init_value = LIZARDS_NROACHESTYPES__POSITION__INIT;
  *message = init_value;
}
size_t lizards_nroachestypes__position__get_packed_size
                     (const LizardsNroachestypes__Position *message)
{
  assert(message->base.descriptor == &lizards_nroachestypes__position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizards_nroachestypes__position__pack
                     (const LizardsNroachestypes__Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizards_nroachestypes__position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizards_nroachestypes__position__pack_to_buffer
                     (const LizardsNroachestypes__Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizards_nroachestypes__position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardsNroachestypes__Position *
       lizards_nroachestypes__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardsNroachestypes__Position *)
     protobuf_c_message_unpack (&lizards_nroachestypes__position__descriptor,
                                allocator, len, data);
}
void   lizards_nroachestypes__position__free_unpacked
                     (LizardsNroachestypes__Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizards_nroachestypes__position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   lizards_nroachestypes__game_message__init
                     (LizardsNroachestypes__GameMessage         *message)
{
  static const LizardsNroachestypes__GameMessage init_value = LIZARDS_NROACHESTYPES__GAME_MESSAGE__INIT;
  *message = init_value;
}
size_t lizards_nroachestypes__game_message__get_packed_size
                     (const LizardsNroachestypes__GameMessage *message)
{
  assert(message->base.descriptor == &lizards_nroachestypes__game_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t lizards_nroachestypes__game_message__pack
                     (const LizardsNroachestypes__GameMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &lizards_nroachestypes__game_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t lizards_nroachestypes__game_message__pack_to_buffer
                     (const LizardsNroachestypes__GameMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &lizards_nroachestypes__game_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LizardsNroachestypes__GameMessage *
       lizards_nroachestypes__game_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LizardsNroachestypes__GameMessage *)
     protobuf_c_message_unpack (&lizards_nroachestypes__game_message__descriptor,
                                allocator, len, data);
}
void   lizards_nroachestypes__game_message__free_unpacked
                     (LizardsNroachestypes__GameMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &lizards_nroachestypes__game_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor lizards_nroachestypes__position__field_descriptors[2] =
{
  {
    "position_x",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardsNroachestypes__Position, position_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LizardsNroachestypes__Position, position_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizards_nroachestypes__position__field_indices_by_name[] = {
  0,   /* field[0] = position_x */
  1,   /* field[1] = position_y */
};
static const ProtobufCIntRange lizards_nroachestypes__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor lizards_nroachestypes__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizardsNroachestypes.Position",
  "Position",
  "LizardsNroachestypes__Position",
  "lizardsNroachestypes",
  sizeof(LizardsNroachestypes__Position),
  2,
  lizards_nroachestypes__position__field_descriptors,
  lizards_nroachestypes__position__field_indices_by_name,
  1,  lizards_nroachestypes__position__number_ranges,
  (ProtobufCMessageInit) lizards_nroachestypes__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor lizards_nroachestypes__game_message__field_descriptors[9] =
{
  {
    "msg_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LizardsNroachestypes__GameMessage, msg_type),
    &lizards_nroachestypes__message_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_roaches",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, has_n_roaches),
    offsetof(LizardsNroachestypes__GameMessage, n_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "n_wasps",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, has_n_wasps),
    offsetof(LizardsNroachestypes__GameMessage, n_wasps),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, has_index),
    offsetof(LizardsNroachestypes__GameMessage, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "roach_index",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, has_roach_index),
    offsetof(LizardsNroachestypes__GameMessage, roach_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wasp_index",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, has_wasp_index),
    offsetof(LizardsNroachestypes__GameMessage, wasp_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "score_roaches",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, n_score_roaches),
    offsetof(LizardsNroachestypes__GameMessage, score_roaches),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wasps_char",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT32,
    offsetof(LizardsNroachestypes__GameMessage, n_wasps_char),
    offsetof(LizardsNroachestypes__GameMessage, wasps_char),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "direction",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(LizardsNroachestypes__GameMessage, has_direction),
    offsetof(LizardsNroachestypes__GameMessage, direction),
    &lizards_nroachestypes__direction_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned lizards_nroachestypes__game_message__field_indices_by_name[] = {
  8,   /* field[8] = direction */
  3,   /* field[3] = index */
  0,   /* field[0] = msg_type */
  1,   /* field[1] = n_roaches */
  2,   /* field[2] = n_wasps */
  4,   /* field[4] = roach_index */
  6,   /* field[6] = score_roaches */
  5,   /* field[5] = wasp_index */
  7,   /* field[7] = wasps_char */
};
static const ProtobufCIntRange lizards_nroachestypes__game_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor lizards_nroachestypes__game_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "lizardsNroachestypes.GameMessage",
  "GameMessage",
  "LizardsNroachestypes__GameMessage",
  "lizardsNroachestypes",
  sizeof(LizardsNroachestypes__GameMessage),
  9,
  lizards_nroachestypes__game_message__field_descriptors,
  lizards_nroachestypes__game_message__field_indices_by_name,
  1,  lizards_nroachestypes__game_message__number_ranges,
  (ProtobufCMessageInit) lizards_nroachestypes__game_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue lizards_nroachestypes__message_type__enum_values_by_number[8] =
{
  { "ROACHES_CONNECT", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__ROACHES_CONNECT", 0 },
  { "ROACHES_MOVEMENT", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__ROACHES_MOVEMENT", 1 },
  { "WASPS_CONNECT", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__WASPS_CONNECT", 2 },
  { "WASPS_MOVEMENT", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__WASPS_MOVEMENT", 3 },
  { "ACK", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__ACK", 4 },
  { "SCORE_UPDATE", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__SCORE_UPDATE", 5 },
  { "ROACHES_DISCONNECT", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__ROACHES_DISCONNECT", 100 },
  { "WASPS_DISCONNECT", "LIZARDS_NROACHESTYPES__MESSAGE_TYPE__WASPS_DISCONNECT", 101 },
};
static const ProtobufCIntRange lizards_nroachestypes__message_type__value_ranges[] = {
{0, 0},{100, 6},{0, 8}
};
static const ProtobufCEnumValueIndex lizards_nroachestypes__message_type__enum_values_by_name[8] =
{
  { "ACK", 4 },
  { "ROACHES_CONNECT", 0 },
  { "ROACHES_DISCONNECT", 6 },
  { "ROACHES_MOVEMENT", 1 },
  { "SCORE_UPDATE", 5 },
  { "WASPS_CONNECT", 2 },
  { "WASPS_DISCONNECT", 7 },
  { "WASPS_MOVEMENT", 3 },
};
const ProtobufCEnumDescriptor lizards_nroachestypes__message_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lizardsNroachestypes.MessageType",
  "MessageType",
  "LizardsNroachestypes__MessageType",
  "lizardsNroachestypes",
  8,
  lizards_nroachestypes__message_type__enum_values_by_number,
  8,
  lizards_nroachestypes__message_type__enum_values_by_name,
  2,
  lizards_nroachestypes__message_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue lizards_nroachestypes__entity_type__enum_values_by_number[3] =
{
  { "NOTHING", "LIZARDS_NROACHESTYPES__ENTITY_TYPE__NOTHING", 0 },
  { "ROACH", "LIZARDS_NROACHESTYPES__ENTITY_TYPE__ROACH", 1 },
  { "WASP", "LIZARDS_NROACHESTYPES__ENTITY_TYPE__WASP", 2 },
};
static const ProtobufCIntRange lizards_nroachestypes__entity_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex lizards_nroachestypes__entity_type__enum_values_by_name[3] =
{
  { "NOTHING", 0 },
  { "ROACH", 1 },
  { "WASP", 2 },
};
const ProtobufCEnumDescriptor lizards_nroachestypes__entity_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lizardsNroachestypes.EntityType",
  "EntityType",
  "LizardsNroachestypes__EntityType",
  "lizardsNroachestypes",
  3,
  lizards_nroachestypes__entity_type__enum_values_by_number,
  3,
  lizards_nroachestypes__entity_type__enum_values_by_name,
  1,
  lizards_nroachestypes__entity_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue lizards_nroachestypes__direction_type__enum_values_by_number[4] =
{
  { "UP", "LIZARDS_NROACHESTYPES__DIRECTION_TYPE__UP", 0 },
  { "DOWN", "LIZARDS_NROACHESTYPES__DIRECTION_TYPE__DOWN", 1 },
  { "LEFT", "LIZARDS_NROACHESTYPES__DIRECTION_TYPE__LEFT", 2 },
  { "RIGHT", "LIZARDS_NROACHESTYPES__DIRECTION_TYPE__RIGHT", 3 },
};
static const ProtobufCIntRange lizards_nroachestypes__direction_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex lizards_nroachestypes__direction_type__enum_values_by_name[4] =
{
  { "DOWN", 1 },
  { "LEFT", 2 },
  { "RIGHT", 3 },
  { "UP", 0 },
};
const ProtobufCEnumDescriptor lizards_nroachestypes__direction_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "lizardsNroachestypes.DirectionType",
  "DirectionType",
  "LizardsNroachestypes__DirectionType",
  "lizardsNroachestypes",
  4,
  lizards_nroachestypes__direction_type__enum_values_by_number,
  4,
  lizards_nroachestypes__direction_type__enum_values_by_name,
  1,
  lizards_nroachestypes__direction_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
